Nobble/Models/Produit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Nobble.Models
{
    [Table("Produit")]
    public class Produit
    {
        [Key]
        public int id { get; set; }
        [Required]
        [MaxLength(15)]
        public string libelle { get; set; }
        [Required]
        public string description { get; set; }
        [Required]
        public float prix { get; set; }
        [Required]
        public bool is_option { get; set; }
    }
}

Nobble/Controllers/AbonnementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nobble.Models;
using System.Diagnostics;
using System.Web.Services;
using Microsoft.AspNet.Identity;

namespace Nobble.Controllers
{
    public class AbonnementsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ProduitsController Produits = new ProduitsController();
        [HttpPost]
        public ActionResult AddAbonnement(string produit_id)
        {
            Produit produit = Produits.GetProduit(Convert.ToInt32(produit_id));
            Abonnement abonnement = new Abonnement();

            if (produit.is_option == false)
            {
                resetAbonnementPrincipal();
            }
            if (!checkUserHaveProduit(Convert.ToInt32(produit_id)))
            {
                abonnement.user_id = User.Identity.GetUserId();
                abonnement.produit_id = Convert.ToInt32(produit_id);
                abonnement.is_option = produit.is_option;
                abonnement.prix = produit.prix;
                abonnement.date_achat = DateTime.Now;
                abonnement.is_actif = false;
                Create(abonnement);
                
            }

            return Json("success", JsonRequestBehavior.AllowGet);
        }

        public Boolean checkUserHaveProduit(int produit_id)
        {
            string user_id = User.Identity.GetUserId();
            return db.Abonnements.Where(Abonnements => Abonnements.user_id == user_id && Abonnements.produit_id == produit_id).Count() > 0;
        }

        public Boolean resetAbonnementPrincipal ()
        {
            string user_id = User.Identity.GetUserId();
            if(db.Abonnements.Where(Abonnements => Abonnements.user_id == user_id && !Abonnements.is_option).Count() > 0)
            {
                Abonnement abonnement = db.Abonnements.Where(Abonnements => Abonnements.user_id == user_id && Abonnements.is_option == false).First();
                db.Abonnements.Remove(abonnement);
                db.SaveChanges();
                return true;
            }
            else
            {
                return false;
            }
            
        }

        // GET: Abonnements
        public ActionResult Index()
        {
            return View(db.Abonnements.ToList());
        }

        // GET: Abonnements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Abonnement abonnement = db.Abonnements.Find(id);
            if (abonnement == null)
            {
                return HttpNotFound();
            }
            return View(abonnement);
        }

        // GET: Abonnements/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Abonnements/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,user_id,produit_id,prix,date_achat,frequence,is_actif")] Abonnement abonnement)
        {
            if (ModelState.IsValid)
            {
                db.Abonnements.Add(abonnement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(abonnement);
        }

        // GET: Abonnements/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Abonnement abonnement = db.Abonnements.Find(id);
            if (abonnement == null)
            {
                return HttpNotFound();
            }
            return View(abonnement);
        }

        // POST: Abonnements/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,user_id,produit_id,prix,date_achat,frequence,is_actif")] Abonnement abonnement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(abonnement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(abonnement);
        }

        // GET: Abonnements/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Abonnement abonnement = db.Abonnements.Find(id);
            if (abonnement == null)
            {
                return HttpNotFound();
            }
            return View(abonnement);
        }

        // POST: Abonnements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Abonnement abonnement = db.Abonnements.Find(id);
            db.Abonnements.Remove(abonnement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Nobble/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nobble.Models;

namespace Nobble.Controllers
{
    public class ProduitsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public Produit GetProduit(int? id)
        {
            if (id == null)
            {
                return null;
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return null;
            }
            return produit;
        }
        public List<Produit> GetProduits()
        {
            return db.Produits.ToList();
        }
        // GET: Produits
        public ActionResult Index()
        {
            return View(db.Produits.ToList());
        }

        public ActionResult Offres()
        {
            ViewBag.FreeMode = db.Produits.Where(Produits => Produits.libelle == "Free Mode").First();
            ViewBag.PremiumMode = db.Produits.Where(Produits => Produits.libelle == "Premium Mode").First();
            return View(db.Produits.Where(Produits => Produits.is_option == true).ToList());
        }


        // GET: Produits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // GET: Produits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produits/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,libelle,description,prix,is_option")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Produits.Add(produit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produit);
        }

        // GET: Produits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: Produits/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,libelle,description,prix,is_option")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(produit);
        }

        // GET: Produits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produit produit = db.Produits.Find(id);
            db.Produits.Remove(produit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Nobble/Views/Produits/Create.cshtml
@model Nobble.Models.Produit

<div class="admin-panel">
    <div class="container">

        @Html.Partial("_Admin-panel")

        <div class="content create-prod">
            <div class="block-text">
                <div class="title">Ajouter un produit</div>
                
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        
                       
                            @Html.EditorFor(model => model.libelle, new { htmlAttributes = new { @class = "form-control button-custom btempty", placeholder="Libelle" } })
                            @Html.ValidationMessageFor(model => model.libelle, "", new { @class = "text-danger" })
                        
                    </div>

                    <div class="form-group">
                        
                       
                            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control button-custom btempty", placeholder = "Description" } })
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                      
                    </div>

                    <div class="form-group">
                        
                       
                            @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control button-custom btempty", placeholder = "Prix en €" } })
                            @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
                    
                    </div>

                    <div class="form-group">
                        
                       
                            <div class="checkbox">
                                @Html.EditorFor(model => model.is_option)
                                @Html.ValidationMessageFor(model => model.is_option, "", new { @class = "text-danger" })
                            </div>
                        @Html.LabelFor(model => model.is_option, htmlAttributes: new { @class = "label" } )
                        
                    </div>

                    <div class="form-group btt">
                        
                            <input type="submit" value="Valider" class="button-custom btempty bt-create" />
                        
                    </div>
                </div>
            }

            

        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Nobble/Views/Produits/Delete.cshtml
@model Nobble.Models.Produit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_option)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_option)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Nobble/Views/Produits/Details.cshtml
@model Nobble.Models.Produit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.is_option)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.is_option)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Nobble/Views/Produits/Edit.cshtml
@model Nobble.Models.Produit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_option, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.is_option)
                    @Html.ValidationMessageFor(model => model.is_option, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Nobble/Views/Produits/Index.cshtml
@model IEnumerable<Nobble.Models.Produit>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.libelle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.is_option)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.libelle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prix)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.is_option)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Nobble/Views/Produits/Offer.cshtml
@model IEnumerable<Nobble.Models.Produit>
<table class="table">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.libelle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.prix)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.is_option)
                </td>
                <td>
                    <select id="select">
                        <option value="1">1Mois</option>
                        <option value="3" >3Mois</option>
                        <option value="12">1An</option>
                    </select>
                </td>
                <td>
                    <input type='button' onclick='AddElement(@item.id)' value='Status Update'>
                </td>
            </tr>
        }
</table>
<script type="text/javascript">
    function AddElement(produit_id) {
        console.log(produit_id);
        $.ajax({
            type: "POST",
            url: '@Url.Action("AddAbonnement", "Abonnements")',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ 'produit_id': produit_id, 'frequence': $('#select').val() }),
            dataType: "json",
            success: function () { console.log('Succes'); },
            error: function () { console.log('Error'); },
        });

};
</script>

Nobble/Views/Produits/Offres.cshtml
@model IEnumerable<Nobble.Models.Produit>

<div id="scene-offres">
    <div class="container">
        <div class="block-title">
            <div class="title">Nos Offres</div>
            
            @if (!Request.IsAuthenticated)
            {
                <div class="subtitle ifnoco">
                    @Html.ActionLink("Connectez vous pour profiter de nos offres !", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
                </div>
            }
            else
            {
                <div class="subtitle">Sélectionnez le forfait qui vous convient.</div>
            }
                </div>
        <div class="block-forfait">
            <div class="forfait one">
               
                    @if (Request.IsAuthenticated)
                    {
                        <div class="vignette" onclick='AddElement(@ViewBag.FreeMode.id )'>
                            <div class="picto-vign free" ></div>
                        </div>
                    }
                    else
                    {
                        <div class="vignette">
                            <div class="picto-vign free" ></div>
                        </div>
                    }
                        
                <div class="title">@ViewBag.FreeMode.libelle</div>
                <div class="text">@ViewBag.FreeMode.description</div>
                <div class="prix">@ViewBag.FreeMode.prix €/Mois</div>
            </div>
            <div class="forfait two">
                
                @if (Request.IsAuthenticated)
                {
                    <div class="vignette" onclick='AddElement(@ViewBag.PremiumMode.id )'>
                        <div class="picto-vign premium"></div>
                    </div>
                }
                else
                {
                    <div class="vignette">
                        <div class="picto-vign premium"></div>
                    </div>
                }

                <div class="title">@ViewBag.PremiumMode.libelle</div>
                <div class="text">@ViewBag.PremiumMode.description</div>
                <div class="prix">@ViewBag.PremiumMode.prix €/Mois</div>
            </div>
            <div class="separator"></div>
        </div>
        <div class="block-modules">
            <div class="title">Les modules</div>
            <div class="subtitle">Sélectionnez les modules complémentaire.</div>
            @foreach (var item in Model)
            {
                <div class="modules">
                    <div class="picto-mod"></div>
                    <div class="libele">@Html.DisplayFor(modelItem => item.libelle)</div>
                    <div class="description">@Html.DisplayFor(modelItem => item.description)</div>
                    <div class="price">@Html.DisplayFor(modelItem => item.prix)€/Mois</div>
                @if (Request.IsAuthenticated)
                {
                    <div class="button-custom btempty bt-ajoutmod" onclick='AddElement(@item.id)'>Ajouter</div>
                }
                </div>
            }
           

        </div>
    </div>
</div>
<script>
function AddElement(produit_id) {
    console.log(produit_id);
    $.ajax({
        type: "POST",
        url: '@Url.Action("AddAbonnement", "Abonnements")',
        contentType: "application/json; charset=utf-8",
        data: JSON.stringify({ 'produit_id': produit_id }),
        dataType: "json",
        success: function () { console.log('Succes'); },
        error: function () { console.log('Error'); },
        });

    };
</script>