Nobble/Controllers/FacturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nobble.Models;
using Microsoft.AspNet.Identity;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;
using System.Web.UI;
using System.Text;
using iTextSharp.text.html.simpleparser;

namespace Nobble.Controllers
{
    public class FacturesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Factures
        public ActionResult Index()
        {
            return View(db.Factures.ToList());
        }

        // GET: Factures/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Facture facture = db.Factures.Find(id);
            if (facture == null)
            {
                return HttpNotFound();
            }
            return View(facture);
        }

        [Authorize]
        public ActionResult MesFactures()
        {
            string user_id = User.Identity.GetUserId();

            List<Facture> factures = new List<Facture>();
            factures = db.Factures.Where(Facture => Facture.user_id == user_id).ToList();
            int i = 0;
            foreach (Facture uneFacture in factures)
            {
                factures[i].abonnements = new List<Abonnement>();
                factures[i].prixTotal = 0;
                List<AbonnementFactures> abofacture = db.AbonnementFactures.Where(af => af.facture_id == uneFacture.id).ToList();
                // si abofacture existe => il y a des produits
                if (abofacture.Count() > 0)
                {
                    foreach(AbonnementFactures unAboFacture in abofacture)
                    {
                        Abonnement unAbonnement = db.Abonnements.Find(unAboFacture.abonnement_id);
                        if(unAbonnement != null)
                        {
                            Produit unProduit = db.Produits.Find(unAbonnement.produit_id);
                            unAbonnement.produit = unProduit;
                            factures[i].abonnements.Add(unAbonnement);
                            factures[i].prixTotal += unProduit.prix;
                        }

                    }
                }
                i++;
            }
            return View(factures);
        }

        [Authorize]
        public ActionResult Pdf(int id)
        {
            return File(this.generatePdf(this.getFactureFromUser(id)), "application/pdf", "Facture-" + id + ".pdf");

        }

        private Facture getFactureFromUser(int id)
        {
            string user_id = User.Identity.GetUserId();

            List<Facture> factures = new List<Facture>();
            factures = db.Factures.Where(Facture => Facture.user_id == user_id && Facture.id == id).ToList();
            int i = 0;
            foreach (Facture uneFacture in factures)
            {
                factures[i].abonnements = new List<Abonnement>();
                factures[i].prixTotal = 0;
                List<AbonnementFactures> abofacture = db.AbonnementFactures.Where(af => af.facture_id == uneFacture.id).ToList();
                // si abofacture existe => il y a des produits
                if (abofacture.Count() > 0)
                {
                    foreach (AbonnementFactures unAboFacture in abofacture)
                    {
                        Abonnement unAbonnement = db.Abonnements.Find(unAboFacture.abonnement_id);
                        if (unAbonnement != null)
                        {
                            Produit unProduit = db.Produits.Find(unAbonnement.produit_id);
                            if (unProduit != null)
                            {
                                unAbonnement.produit = unProduit;
                            }
                            factures[i].abonnements.Add(unAbonnement);
                            factures[i].prixTotal += unProduit.prix;
                        }

                    }
                }
                i++;
            }
            if (factures.Count() > 0)
            {
                return factures[0];
            }

            return new Facture();
        }

        private MemoryStream generatePdf(Facture facture)
        {
            MemoryStream stream = new MemoryStream();

            string companyName = "Nobble Corporation";
            string orderNo = "ID-" + facture.id;
            DataTable dt = new DataTable();
            dt.Columns.AddRange(new DataColumn[4] {
                            new DataColumn("Référence produit", typeof(string)),
                            new DataColumn("Produit", typeof(string)),
                            new DataColumn("Description", typeof(string)),
                            new DataColumn("Prix", typeof(float))});
            foreach (Abonnement unAbonnement in facture.abonnements)
            {
                dt.Rows.Add(
                    "ID-" + unAbonnement.id, 
                    unAbonnement.produit.libelle, 
                    unAbonnement.produit.description,
                    unAbonnement.prix
               );
            }

            using (StringWriter sw = new StringWriter())
            {
                using (HtmlTextWriter hw = new HtmlTextWriter(sw))
                {
                    StringBuilder sb = new StringBuilder();

                    sb.Append("<table width='100%' cellspacing='0' cellpadding='2'>");
                    sb.Append("<tr><td align='center' style='background-color: #18B5F0' colspan = '2'><b>Commande</b></td></tr>");
                    sb.Append("<tr><td colspan = '2'></td></tr>");
                    sb.Append("<tr><td><b>Order No: </b>");
                    sb.Append(orderNo);
                    sb.Append("</td><td align = 'right'><b>Date facturation: </b>");
                    sb.Append(facture.date_facture.ToShortDateString());
                    sb.Append(" </td></tr>");
                    sb.Append("<tr><td colspan = '2'><b>Entreprise: </b>");
                    sb.Append(companyName);
                    sb.Append("</td></tr>");
                    sb.Append("</table>");
                    sb.Append("<br />");

                    //Generate Invoice (Bill) Items Grid.
                    sb.Append("<table border = '1'>");
                    sb.Append("<tr>");
                    foreach (DataColumn column in dt.Columns)
                    {
                        sb.Append("<th style = 'background-color: #ffffff;color:#000000'>");
                        sb.Append(column.ColumnName);
                        sb.Append("</th>");
                    }
                    sb.Append("</tr>");
                    foreach (DataRow row in dt.Rows)
                    {
                        sb.Append("<tr>");
                        foreach (DataColumn column in dt.Columns)
                        {
                            sb.Append("<td>");
                            sb.Append(row[column]);
                            sb.Append("</td>");
                        }
                        sb.Append("</tr>");
                    }
                    sb.Append("<tr><td align = 'right' colspan = '");
                    sb.Append(dt.Columns.Count - 1);
                    sb.Append("'>Total</td>");
                    sb.Append("<td>");
                    sb.Append(dt.Compute("sum(Prix)", ""));
                    sb.Append("</td>");
                    sb.Append("</tr></table>");

                    //Export HTML String as PDF.
                    StringReader sr = new StringReader(sb.ToString());
                    Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 10f, 0f);
                    Image img = Image.GetInstance(Server.MapPath("~/Content/images/commun/logo.png"));
                    img.ScaleToFit(80f, 80f);
#pragma warning disable CS0612 // 'HTMLWorker' is obsolete
#pragma warning disable CS0612 // 'HTMLWorker' is obsolete
                    HTMLWorker htmlparser = new HTMLWorker(pdfDoc);
#pragma warning restore CS0612 // 'HTMLWorker' is obsolete
#pragma warning restore CS0612 // 'HTMLWorker' is obsolete
                    PdfWriter writer = PdfWriter.GetInstance(pdfDoc, Response.OutputStream);
                    pdfDoc.Open();
                    pdfDoc.Add(img);

                    htmlparser.Parse(sr);
                    pdfDoc.Close();
                    Response.ContentType = "application/pdf";
                    Response.AddHeader("content-disposition", "attachment;filename=Facture_" + orderNo + ".pdf");
                    Response.Cache.SetCacheability(HttpCacheability.NoCache);
                    Response.Write(pdfDoc);
                    Response.End();
                }
            }
            stream.Flush();
            stream.Position = 0;
            return stream;
        }



        // GET: Factures/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Factures/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,user_id,date_facture")] Facture facture)
        {
            if (ModelState.IsValid)
            {
                db.Factures.Add(facture);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(facture);
        }

        // GET: Factures/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {

Nobble/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nobble.Models;

namespace Nobble.Controllers
{
    public class ProduitsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public Produit GetProduit(int? id)
        {
            if (id == null)
            {
                return null;
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return null;
            }
            return produit;
        }
        public List<Produit> GetProduits()
        {
            return db.Produits.ToList();
        }
        // GET: Produits
        public ActionResult Index()
        {
            return View(db.Produits.ToList());
        }

        public ActionResult Offres()
        {
            ViewBag.FreeMode = db.Produits.Where(Produits => Produits.libelle == "Free Mode").First();
            ViewBag.PremiumMode = db.Produits.Where(Produits => Produits.libelle == "Premium Mode").First();
            return View(db.Produits.Where(Produits => Produits.is_option == true).ToList());
        }


        // GET: Produits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // GET: Produits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produits/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,libelle,description,prix,is_option")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Produits.Add(produit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produit);
        }

        // GET: Produits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: Produits/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,libelle,description,prix,is_option")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(produit);
        }

        // GET: Produits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produit produit = db.Produits.Find(id);
            db.Produits.Remove(produit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Nobble/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using  Nobble.Models;
@{ 
    var list = (List<Produit>)Session["Panier"];
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div id="headers">
        <div class="container">
            <div class="logo-main"><a href="/"></a></div>
            <div class="menu-main">

                <ul>
                    <li>@Html.ActionLink("Nous", "About", "Home")</li>
                    <li>@Html.ActionLink("Offres", "Offres", "Produits")</li>
                    <li>@Html.ActionLink("Engagements", "Engagements", "Home")</li>
                    @if (Request.IsAuthenticated)
            {
                        <li id="name-user-co">
                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                            {
                            @Html.AntiForgeryToken()

                           @User.Identity.GetUserName()
                            <ul class="down-menu">
                                <li>@Html.ActionLink("Mon compte", "Offre", "Manage")</li>
                                <li><a href="javascript:document.getElementById('logoutForm').submit()">Se déconnecter</a></li>
                            </ul>

                            }
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Se Connecter", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" , @class = "li-seco" })</li>
                    }
                </ul>
                    <div class="panier">
                        <div class="compteur"><span class="number"></span>0</div>
                    </div>
            </div>
            <div class="menu-mobile" id="menu-mobile-bt">
                <div class="hamburger one"></div>
                <div class="hamburger two"></div>
                <div class="hamburger three"></div>
            </div>

            <div class="view-panier">
                @if (Request.IsAuthenticated)
                {
                    <div id="panier-content">
                        <div class="block-myforfait">
                            <div class="myforfait">
                                <div class="vignette">
                                    <div id="forfaitIcon"></div>
                                </div>
                                <div id="forfaitTitle" class="title"></div>
                            </div>
                            <div class="separator"></div>
                        </div>
                        <div id="block-modules" class="block-modules">
                        </div>
                        <div class="button-custom pink bt-viewcompte">@Html.ActionLink("Mon Forfait", "Offre", "Manage")</div>
                    </div>
                    <div id="panier-vide">
                        <div class="title">Votre panier est vide</div>
                        <div class="button-custom pink bt-viewcompte">
                            @Html.ActionLink("Nos offres", "Offres", "Produits")
                        </div>
                    </div>
                }
                else
                {

                    <div class="title">Connectez-vous pour afficher votre panier</div>
                    <div class="button-custom pink bt-viewcompte">
                        @Html.ActionLink("Par ici", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
                    </div>

                 }

                </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        
    </div>

    <footer>
        <div id="footer">
            <div class="container">
                <div class="block-store">
                    <div class="icone icone-ios"></div>
                    <div class="icone icone-android"></div>
                </div>
                <ul class="menu-footer">
                    <li>@Html.ActionLink("Mentions légales", "Mentions", "Home")</li>
                    <li>@Html.ActionLink("Contactez-nous", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Nos offres", "Offres", "Produits")</li>
                    <li>@Html.ActionLink("Notre équipe", "About", "Home")</li>
                </ul>
               
                <div class="copyright">©Nobble 2017. Tous droits réservés</div>

                
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
@if (Request.IsAuthenticated)
{
    <script>
        setInterval(function () {
            $.ajax({
                type: "POST",
                url: '@Url.Action("userPanier", "Manage")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                Object.keys(response).length;
                $("#block-modules").html("");
                response.forEach(function (element) {
                    if (element.is_option == false) {
                        $('#forfaitTitle').text(element.produit.libelle);
                        $('#forfaitIcon').removeClass();
                        if (element.produit.libelle == "Premium Mode") {
                            $('#forfaitIcon').addClass("picto-vign premium");
                        } else {
                            $('#forfaitIcon').addClass("picto-vign free");

                        }
                    } else {
                        var template = `<div class="modules">
                                    <div class="picto-mod"></div>
                                    <div class="libele">${element.produit.libelle} </div>
                                    <div class="button-custom btempty bt-ajoutmod" onclick="removeItemPanier(${element.produit.id})">Supprimer</div>
                                </div>`;
                        $('#block-modules').append(template);
                    }
                });
            },
            error: function () { console.log('Error'); },
        });
        }, 500);

        setInterval(function () {
            $.ajax({
                type: "POST",
                url: '@Url.Action("countUserPanier", "Manage")',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    $('.compteur').text(response);
                    if (response > 0) {
                        $('#panier-content').show();
                        $('#panier-vide').hide();
                    } else {
                        $('#panier-vide').show();
                        $('#panier-content').hide();
                    }
                },
                error: function () { console.log('Error'); },
                });
        }, 500);

        function removeItemPanier(produit_id) {
                console.log(produit_id);
            $.ajax({
                type: "POST",
                url: '@Url.Action("removeItemPanier", "Manage")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({ 'produit_id': produit_id }),
                dataType: "json",
                success: function () { console.log('Succes'); },
                error: function () { console.log('Error'); },
                });
        }
    </script>
}

Nobble/Views/Shared/_admin-panel.cshtml
@using Microsoft.AspNet.Identity
<div class="admin-bar">
    <div class="block-user-info">
        <div class="bulle-icone"><div class="icone"></div></div>
        <div class="block-info">
            <div class="email">@User.Identity.GetUserName()</div>
        </div>
    </div>


    <div class="admin-part block-offres">

        <div class="picture"></div>
        <div class="title">@Html.ActionLink("Mon offre", "Offre", "Manage")</div>
        <div class="arrow"></div>

    </div>

    <div class="admin-part block-changemdp">
        <div class="picture"></div>
        <div class="title">@Html.ActionLink("Mot de passe", "ChangePassword", "Manage")</div>
        <div class="arrow"></div>
    </div>
    <div class="admin-part block-facture">
        <div class="picture"></div>
        <div class="title">@Html.ActionLink("Mes factures", "MesFactures", "Factures")</div>
        <div class="arrow"></div>
    </div>
    @if (User.IsInRole("admin"))
    {
        <div class="admin-part block-addproduct">
            <div class="picture"></div>
            <div class="title">@Html.ActionLink("Produits", "Create", "Produits")</div>
            <div class="arrow"></div>
        </div>
            <div class="admin-part block-allfacture">
                <div class="picture"></div>
                <div class="title">@Html.ActionLink("Les Factures", "Index", "Factures")</div>
                <div class="arrow"></div>
            </div>
    }
</div>